---
name: Build KernelSU Next
env:
  TZ: Asia/Shanghai
  ANDROID_VERSION: android15
  KERNEL_VERSION: "6.6"
  KERNEL_NAME: android15-8-g29d86c5fc9dd-abogki428889875-4k
on:
  workflow_dispatch:
    inputs:
      SUSFS:
        description: "📦 SuSFS Support"
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "Off"
      ksunext_multimanager:
        description: "👥 Multimanager support（weishu KSU、5ec1cff KSU、rsuntk KSU、SukiSU Ultra, ReSukiSU, kowsu, MamboSU, WildKSU）"
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "On"
      bbg:
        description: "🛡️ BBG baseband protection"
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "On"
      bbr:
        description: "📶 BBR algorithm (Has little practical benefit for everyday phone use and may even result in negative optimization)"
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "Off"
      adios_rekernel_enable:
        description: "⚙️ ADIOS I/O scheduler and Re-Kernel support"
        required: true
        type: choice
        default: "ADIOS only"
        options:
          - "none"
          - "ADIOS only"
          - "Re-Kernel only"
          - "both"
      proxy:
        description: "🌐 Proxy performance optimization"
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "On"
      UNICODE_BYPASS:
        description: "🚀 Unicode zero-width bypass fix patch (Not recommended for higher kernel versions; it is suggested to use https://t.me/real5ec1cff/271 for a painless fix) "
        required: true
        type: choice
        options:
          - "On"
          - "Off"
        default: "Off"
      kernel_suffix:
        description: "📝 Kernel suffix (Leave empty to use the default; do not add a hyphen at the beginning, and do not include spaces or other reserved characters that may affect command execution)"
        required: false
        type: string
        default: ""
      BUILD_TIME:
        type: string
        description: "📅 Custom build time (Enter F to use the current UTC time)"
        required: false
        default: "Thu Dec 11 04:17:27 UTC 2025"
jobs:
  build:
    name: SUSFS ${{ github.event.inputs.SUSFS }} | BBG ${{ github.event.inputs.bbg }} | ADIOS/Re-Kernel ${{ github.event.inputs.adios_rekernel_enable }}
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_MAXSIZE: 8G
    steps:
      - name: 🚀 Maximize Build Space | 最大化构建空间
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 4096
          remove-dotnet: "true"
          remove-android: "true"
          remove-haskell: "true"
          remove-codeql: "true"

      - name: ⚙️ Setup Cache Env | 设置缓存环境
        run: |
          echo "🔧 正在设置机型隔离缓存目录..."
          echo "CCACHE_DIR=$HOME/.ccache_KSUNext" >> $GITHUB_ENV
          mkdir -p "$HOME/.ccache_KSUNext"

          echo "✅ 缓存目录已设置: $HOME/.ccache_KSUNext"
          
      - name: 🔐 Configure Git | 配置Git账户
        run: |
          echo "🔧 正在配置Git用户信息..."
          git config --global user.name "GitHub Actions - chenhua13 Kernel"
          git config --global user.email "builder@localhost"
          echo "✅ Git配置完成"
          
      - name: 📦 Cache & Install Dependencies | 缓存 & 安装构建依赖
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: python3 git curl ccache libelf-dev build-essential flex bison
            libssl-dev libncurses-dev liblz4-tool zlib1g-dev libxml2-utils rsync
            unzip gawk dos2unix
          execute_install_scripts: true
          
      - name: 💾 Restore ccache (With SUSFS) | 恢复ccache缓存 (With SUSFS)
        if: ${{ github.event.inputs.SUSFS == 'On' }}
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ github.ref }}-KSUNext-SUSFS
          restore-keys: >
            ccache-${{ runner.os }}-KSUNext-SUSFS

            ccache-${{ runner.os }}-KSUNext-SUSFS
            
      - name: 💾 Restore ccache (Without SUSFS) | 恢复ccache缓存 (Without SUSFS)
        if: ${{ github.event.inputs.SUSFS == 'Off' }}
        uses: actions/cache@v3
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ runner.os }}-${{ github.ref }}-KSUNext-NoSUSFS
          restore-keys: >
            ccache-${{ runner.os }}-KSUNext-NoSUSFS

            ccache-${{ runner.os }}-KSUNext-NoSUSFS
            
      - name: ⚙️ Initialize ccache | 初始化ccache
        run: |
          echo "🔧 正在初始化ccache..."
          INIT_FLAG="${{ env.CCACHE_DIR }}/.ccache_initialized"

          if command -v ccache >/dev/null 2>&1; then
            if [ ! -f "$INIT_FLAG" ]; then
              mkdir -p "${{ env.CCACHE_DIR }}"
              ccache -M ${{ env.CCACHE_MAXSIZE }}
              touch "$INIT_FLAG"
              echo "✅ ccache初始化完成"
            else
              echo "ℹ️ ccache已存在，跳过初始化"
            fi
          else
            echo "⚠️ 未找到ccache命令，跳过初始化"
          fi
          # 显示缓存统计
          ccache -s
          echo "✅ ccache初始化流程完成"
          
      - name: 📥 Install Repo Tool | 安装Repo工具
        run: |
          echo "⬇️ 正在下载repo工具..."
          curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

          echo "✅ repo工具安装完成"
          
      - name: 📥 Install Neutron Clang Tool | 安装Neutron Clang工具
        run: |
          echo "⬇️ 正在下载rneutron clang具..."
          mkdir -p "$HOME/toolchains/neutron-clang"
          cd "$HOME/toolchains/neutron-clang"
          bash <(curl -s "https://raw.githubusercontent.com/Neutron-Toolchains/antman/main/antman") -S

          echo "✅ neutron clang工具安装完成"
          
      - name: "⬇️ Clone Kernel Source | 克隆内核源码"
        run: |
          mkdir kernel_workspace && cd kernel_workspace

          echo "🌐 正在初始化内核仓库..."
          repo init -u https://github.com/mrcxlinux/actions_oplus_sm8750.git -b refs/heads/staging -m manifest.xml --depth=1

          echo "🔄 同步代码库(使用$(nproc --all)线程)..."
          repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
          
          rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
          rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
          
          # Remove -dirty in kernel version
          sed -i 's/ -dirty//g' kernel_platform/common/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i 's/ -dirty//g' kernel_platform/external/dtc/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/common/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/msm-kernel/scripts/setlocalversion
          sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' kernel_platform/external/dtc/scripts/setlocalversion

          echo "✅ 内核配置完成"
          
      - name: ⚡ Setup Baseband-guard | 配置 Baseband-guard
        if: ${{ github.event.inputs.bbg == 'On' }}
        run: |
          set -e
          cd kernel_workspace/kernel_platform/common

          echo "🛠️ 正在设置BBG..."
          curl -sSL https://github.com/vc-teahouse/Baseband-guard/raw/main/setup.sh -o setup.sh

          bash setup.sh     
              
      - name: "⚡ Setup KernelSU Next | 配置 KernelSU Next"
        run: |
          cd kernel_workspace/kernel_platform
          # 下载并执行设置脚本
          echo "🛠️ 正在设置KernelSU Next..."
          curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/dev-susfs/kernel/setup.sh" | bash -s dev-susfs

          cd KernelSU-Next
          KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/KernelSU-Next/KernelSU-Next/commits?sha=dev&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile

          if [ "${{ github.event.inputs.ksunext_multimanager }}" == "On" ]; then
               echo "📦 正在启用multimanager支持..."
               curl -L "https://raw.githubusercontent.com/mrcxlinux/kernel_patches/refs/heads/main/ksun/kernelsu-next_multimanager.patch" -o "kernelsu-next_multimanager.patch"
               patch -p1 < kernelsu-next_multimanager.patch
          fi

          echo "✅ KernelSU Next 配置完成"

      - name: "🔧 Setup Patches | 配置补丁"
        run: |
          cd kernel_workspace

          echo "⬇️ 下载所需补丁..."
          if [ "${{ github.event.inputs.SUSFS }}" == "On" ]; then          
            git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android15-6.6
          fi
          git clone https://github.com/mrcxlinux/kernel_patches.git
          git clone https://github.com/ShirkNeko/SukiSU_patch.git

          cd kernel_platform
          echo "📝 复制补丁文件..."
          if [ "${{ github.event.inputs.SUSFS }}" == "On" ]; then
            cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android15-6.6.patch ./common/
            cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
            cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
          else
            cp ../kernel_patches/susfs/scope_min_manual_hooks_v1.9.patch ./common/
          fi

          cp ../kernel_patches/zram/001-lz4.patch ./common/
          cp ../kernel_patches/zram/lz4armv8.S ./common/lib
          cp ../kernel_patches/zram/002-zstd.patch ./common/
          
          if [ "${{ github.event.inputs.UNICODE_BYPASS }}" = "On" ]; then
            cp ../kernel_patches/common/unicode_bypass_fix_6.1+.patch ./common/unicode_bypass_fix.patch
          fi
          
          echo "🔧 应用补丁..."
          cd ./common

          if [ "${{ github.event.inputs.UNICODE_BYPASS }}" = "On" ]; then
            echo "📦 正在应用Unicode零宽绕过修复补丁..."
            patch -p1 < unicode_bypass_fix.patch
          fi

          echo "📦 应用lz4补丁..."
          git apply -p1 < 001-lz4.patch || true

          if [ "${{ github.event.inputs.SUSFS }}" == "On" ]; then 
            echo "📦 应用SUSFS补丁..."
            patch -p1 < 50_add_susfs_in_gki-android15-6.6.patch || true
            cp ../../kernel_patches/69_hide_stuff.patch ./
            patch -p1 -F 3 < 69_hide_stuff.patch
          else
            echo "📦 应用MANUAL_HOOK补丁..."
            patch -p1 --fuzz=3 < scope_min_manual_hooks_v1.9.patch
          fi

          echo "📦 设置 POLLY..."
          cp ../../kernel_patches/common/EnablePOLLY.patch ./
          patch -p1 -F 3 < EnablePOLLY.patch
          
          echo "✅ 所有补丁应用完成"

      - name: ⚙️ Configure Kernel Options | 配置内核选项
        run: |
          cd kernel_workspace/kernel_platform

          echo "⚙️ 正在配置内核编译选项..."

          DEFCONFIG_PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/common/arch/arm64/configs/gki_defconfig"

          # Add KSU configuration settings
          echo "📦 启用 KSU 支持..."
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig  
            
          if [ "${{ github.event.inputs.SUSFS }}" == "On" ]; then
            echo "📦 启用 SUSFS 功能..."
            echo "CONFIG_KSU_SUSFS=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_SUSFS_SUS_MAP=y" >> ./common/arch/arm64/configs/gki_defconfig
          else 
            echo "📦 启用 MANUAL_HOOK..."
            echo "CONFIG_KSU_SUSFS=n" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_KSU_MANUAL_HOOK=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi

          echo "📦 添加对 Mountify (backslashxx/mountify) 模块的支持"
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig


          if [ "${{ github.event.inputs.bbg }}" == "On" ]; then
            echo "⚡ 配置 BBG 中..."
            echo 'CONFIG_BBG=y' >> ./common/arch/arm64/configs/gki_defconfig
            echo 'CONFIG_LSM="landlock,lockdown,yama,loadpin,safesetid,integrity,selinux,smack,tomoyo,apparmor,bpf,baseband_guard"' >> ./common/arch/arm64/configs/gki_defconfig
          fi          

          if [ "${{ github.event.inputs.bbr }}" == "On" ]; then
            echo "🌐 启用 BBR 网络算法..."
            echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_BBR=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_NET_SCH_FQ=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_BIC=n" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_TCP_CONG_HTCP=n" >> ./common/arch/arm64/configs/gki_defconfig
          fi
                 
          # Add O2 config
          echo "📦 设置 O2..."
          echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> ./common/arch/arm64/configs/gki_defconfig
          
          # Enable POLLY in LLVM
          echo "📦 设置 POLLY..."
          echo "CONFIG_LLVM_POLLY=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_LD_DEAD_CODE_DATA_ELIMINATION=y" >> ./common/arch/arm64/configs/gki_defconfig

          if [ "${{ github.event.inputs.proxy }}" == "On" ]; then
            # Add proxy config
            echo "📦 加入代理优化..."
            echo "CONFIG_BPF_STREAM_PARSER=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_NETFILTER_XT_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_MAX=65534" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_BITMAP_IP=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_BITMAP_IPMAC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_BITMAP_PORT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IP=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPMARK=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPPORT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPPORTIP=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPPORTNET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_IPMAC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_MAC=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NETPORTNET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NETNET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NETPORT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_HASH_NETIFACE=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP_SET_LIST_SET=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP6_NF_NAT=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_IP6_NF_TARGET_MASQUERADE=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi

          if [[ "${{ github.event.inputs.adios_rekernel_enable }}" == "ADIOS only" || "${{ github.event.inputs.adios_rekernel_enable }}" == "both" ]]; then
            echo "📦 正在设置 ADIOS..."
            echo "CONFIG_MQ_IOSCHED_ADIOS=y" >> ./common/arch/arm64/configs/gki_defconfig
            echo "CONFIG_MQ_IOSCHED_DEFAULT_ADIOS=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi

          if [[ "${{ github.event.inputs.adios_rekernel_enable }}" == "Re-Kernel only" || "${{ github.event.inputs.adios_rekernel_enable }}" == "both" ]]; then
            echo "📦 正在设置 Re-Kernel..."
            echo "CONFIG_REKERNEL=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi

          #跳过将uapi标准头安装到 usr/include 目录的不必要操作，节省编译时间
          echo "CONFIG_HEADERS_INSTALL=n" >> ./common/arch/arm64/configs/gki_defconfig

          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki

          echo "✅ 内核配置更新完成"
          
      - name: 📦 Add build name | 添加制作名称
        run: |
          echo "📦 替换内核版本后缀..."

          cd $GITHUB_WORKSPACE/kernel_workspace/kernel_platform/

          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            echo "当前内核版本后缀：${{ github.event.inputs.kernel_suffix }}"
            for f in ./common/scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ github.event.inputs.kernel_suffix }}\"|" "$f"
            done
            sudo sed -i 's/-4k/-${{ github.event.inputs.KERNEL_SUFFIX }}/g' ./common/arch/arm64/configs/gki_defconfig
          else
            echo "当前内核版本后缀：${{ env.KERNEL_NAME }}"
            for f in ./common/scripts/setlocalversion; do
              sed -i "\$s|echo \"\\\$res\"|echo \"-${{ env.KERNEL_NAME }}\"|" "$f"
            done
            sudo sed -i 's/-4k/-${{ env.KERNEL_NAME }}/g' ./common/arch/arm64/configs/gki_defconfig
          fi

          sed -i 's/${scm_version}//' ./common/scripts/setlocalversion

          echo "CONFIG_LOCALVERSION_AUTO=n" >> ./common/arch/arm64/configs/gki_defconfig
          
      - name: 📅 Set up custom BUILD_TIME | 设置自定义 BUILD_TIME
        shell: bash
        run: |
          INPUT_TIME="${{ github.event.inputs.BUILD_TIME }}"
          if [[ -n "$INPUT_TIME" && "$INPUT_TIME" != "F" && "$INPUT_TIME" != "f" ]]; then
            DATESTR="$INPUT_TIME"
            echo "Using input BUILD_TIME: $DATESTR"
          else
            DATESTR="$(TZ='UTC' date +'%a %b %d %T %Z %Y')"
            echo "Using UTC time as fallback: $DATESTR"
          fi
          echo "KBUILD_BUILD_TIMESTAMP=${DATESTR}" >> "$GITHUB_ENV"
          echo "KBUILD_BUILD_VERSION=1" >> "$GITHUB_ENV"
          cd $GITHUB_WORKSPACE/kernel_workspace/kernel_platform/
          for f in common/scripts/mkcompile_h msm-kernel/scripts/mkcompile_h; do
            if [ -f "$f" ]; then
              echo "Patching mkcompile_h with BUILD_TIME=$DATESTR"
              if grep -q 'UTS_VERSION=' "$f"; then
                perl -pi -e "s{UTS_VERSION=\"\\\$\\(.*?\\)\"}{UTS_VERSION=\"#1 SMP PREEMPT $DATESTR\"}" "$f"
              else
                perl -0777 -pi -e "s{cat <<EOF}{cat <<EOF\n#undef UTS_VERSION\n#define UTS_VERSION \"#1 SMP PREEMPT $DATESTR\" } unless /UTS_VERSION/" "$f"
              fi
            fi
          done
          
      - name: 🔨 Build Kernel | 编译内核
        run: |
          echo "🏗️ 开始内核编译..."
            export PATH="/usr/lib/ccache:$HOME/toolchains/neutron-clang/bin:$PATH" 
            export PATH="/usr/lib/ccache:$PATH"
            sudo apt install libelf-dev
            cd kernel_workspace/kernel_platform/common
            wget https://github.com/cctv18/oppo_oplus_realme_sm8750/raw/refs/heads/main/lib/libfakestat.so
            wget https://github.com/cctv18/oppo_oplus_realme_sm8750/raw/refs/heads/main/lib/libfaketimeMT.so
            chmod 777 ./*.so
            export FAKESTAT="2025-05-25 12:00:00"
            export FAKETIME="@2025-05-25 13:00:00"
            echo "FAKESTAT=$FAKESTAT" >> $GITHUB_ENV
            echo "FAKETIME=$FAKETIME" >> $GITHUB_ENV
            SO_DIR=$(pwd)
            export PRELOAD_LIBS="$SO_DIR/libfakestat.so $SO_DIR/libfaketimeMT.so"
            #创建 CC (编译器) 包装器
            echo '#!/bin/bash' > cc-wrapper
            echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> cc-wrapper
            echo 'export FAKESTAT="'$FAKESTAT'"' >> cc-wrapper
            echo 'export FAKETIME="'$FAKETIME'"' >> cc-wrapper
            echo 'ccache clang "$@"' >> cc-wrapper
            #创建 LD (链接器) 包装器
            echo '#!/bin/bash' > ld-wrapper
            echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> ld-wrapper
            echo 'export FAKESTAT="'$FAKESTAT'"' >> ld-wrapper
            echo 'export FAKETIME="'$FAKETIME'"' >> ld-wrapper
            echo 'ld.lld "$@"' >> ld-wrapper

            # 测试时间劫持测试是否正常工作
            echo "--- [Wrapper Test] 正在创建通用的时间劫持测试脚本 ---"
            echo '#!/bin/bash' > test-wrapper.sh
            echo 'export LD_PRELOAD="'$PRELOAD_LIBS'"' >> test-wrapper.sh
            echo 'export FAKESTAT="'$FAKESTAT'"' >> test-wrapper.sh
            echo 'export FAKETIME="'$FAKETIME'"' >> test-wrapper.sh
            echo 'echo ">>> Wrapper 内部环境检查完毕."' >> test-wrapper.sh
            echo 'exec "$@"' >> test-wrapper.sh # 执行所有传入的参数
            chmod +x test-wrapper.sh
            echo "--- [Wrapper Test] 正在测试 (date) 命令 ---"
            ./test-wrapper.sh date
            echo "--- [Wrapper Test] 正在测试 (stat) 命令 ---"
            ./test-wrapper.sh stat ./Makefile
            echo "--- [Wrapper Test] 测试完毕 ---"
            chmod +x cc-wrapper ld-wrapper
            echo "--- 编译前环境时间: $(LD_PRELOAD=$PRELOAD_LIBS date) ---"
            echo "--- 编译前环境文件时间戳: ---"
            LD_PRELOAD=$PRELOAD_LIBS stat ./Makefile
            make -j$(nproc --all) LLVM=1 LLVM_IAS=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld HOSTLD=ld.lld O=out KCFLAGS+=-O2  gki_defconfig all

          # 显示ccache统计信息
          ccache -s

          echo "✅ 内核编译完成"
          
      - name: 📦 Package Kernel | 打包内核
        run: |
          echo "📦 准备AnyKernel3打包环境..."
          git clone https://github.com/mrcxlinux/AnyKernel3 --depth=1
          rm -rf ./AnyKernel3/.git
          mkdir -p kernel_workspace/kernel_platform/out/Final-Image-Find/

          dir1=""
          dir2=""

          image_path=$(find "./kernel_workspace/kernel_platform/common/out/" -name "Image" | head -n 1)

          if [ -n "$image_path" ]; then
            dir1=$(dirname "$image_path")/
            echo "✅ 成功找到 Image 文件"
          fi

          if [ -n "$image_path" ] && [ -f "$image_path" ]; then
            echo "Image file finally located at: $image_path"
            cp "$image_path" ./AnyKernel3/Image
            cp "$image_path" kernel_workspace/kernel_platform/out/Final-Image-Find/Image
          fi

      - name: 🧠 Set Artifact Name | 设置产物名称
        id: set_name
        run: |
          BASE_NAME="KSUNext_Ultra_lz4_${{ env.KSUVER }}"
          
          if [ "${{ github.event.inputs.SUSFS }}" = "On" ]; then
            FINAL_NAME="${BASE_NAME}_SUSFS"
          else
            FINAL_NAME="${BASE_NAME}"
          fi

          echo "ARTIFACT_NAME=${FINAL_NAME}" >> $GITHUB_OUTPUT
          
      - name: 📤 Upload AnyKernel3 | 上传 AnyKernel3
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.set_name.outputs.ARTIFACT_NAME }}
          path: ./AnyKernel3/*

      - name: 📝 Make ZRAM module | 制作 ZRAM 模块
        run: |
          set -e
          echo "📥 正在下载 zram.zip…"
          curl -L "https://github.com/cctv18/oppo_oplus_realme_sm8750/raw/refs/heads/main/zram.zip" -o "$GITHUB_WORKSPACE/zram.zip"
          
          echo "📦 正在解压…"
          unzip -q "$GITHUB_WORKSPACE/zram.zip" -d "$GITHUB_WORKSPACE/zram"
          
          echo "🔁 正在替换 zram.ko…"
          find "$GITHUB_WORKSPACE/zram" -name "zram.ko" -exec cp "./kernel_workspace/kernel_platform/common/out/drivers/block/zram/zram.ko" {} \;
          rm -rf $GITHUB_WORKSPACE/zram.zip
          
          echo "📦 正在重新打包 zip…"
          cd "$GITHUB_WORKSPACE/zram"
          zip -qr "../zram.zip" .
          
          echo "✅ 完成！"

      - name: 📤 Upload zram.zip | 上传 zram.zip
        uses: actions/upload-artifact@v4
        with:
          name: zram-module.zip
          path: ./zram.zip
